name: Loruki CI/CD Pipepline

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    #  Job 1: Test
    test:
        name: Lint & Unit Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
                cache: 'pip'

            - name: Install dependencies
              run: |
                pip install -r backend/requirements.txt
                pip install flake8 black pytest pytest-cov

            # - name: Lint test with flake8
            #   run: flake8 backend/ 

            # - name: Check formatting with black
            #   run: black --check backend/

            - name: Security scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: CRITICAL,HIGH
        
    build-and-push:
        name: Build and Push Image to ECR
        runs-on: ubuntu-latest
        needs: [test]
        
        steps:
            - name: DO NOTHING
              run: uname




            


            
