name: Loruki CI/CD Pipepline

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:


env:
    AWS_REGION: ${{ secrets.AWS_REGION }}
    FRONTEND_IMAGE: loruki_app/frontend
    BACKEND_IMAGE: loruki_app/backend
    POSTGRES_IMAGE: loruki_app/postgres

jobs:
    #  Job 1: Test
    test:
        name: Lint & Unit Test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                python-version: '3.13'
                cache: 'pip'

            - name: Install dependencies
              run: |
                pip install -r backend/requirements.txt
                pip install flake8 black pytest pytest-cov

            # - name: Lint test with flake8
            #   run: flake8 backend/ 

            # - name: Check formatting with black
            #   run: black --check backend/

            - name: Security scan
              uses: aquasecurity/trivy-action@v0.36.0
              with:
                scan-type: 'fs'
                ignore-unfixed: true
                format: 'sarif'
                output: 'trivy-results.sarif'
                severity: CRITICAL,HIGH
        
    build-frontend:
        name: Build and Push Frontend Image to ECR
        runs-on: ubuntu-latest
        needs: [test]
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Generate image metadata
              id: meta
              run: |
                SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
                echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
                echo "Image tag: ${SHORT_SHA}"

              
            - name: Build & Push frontend Image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: hexagon-ecr
                IMAGE_TAG: loruki_frontend
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend/
                docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-${{ github.run_number }}
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-${{ github.run_number }}

            - name: Notify ECR Push
              run: |
                aws sns publish \
                  --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
                  --subject "New Loruki Image Pushed to ECR" \
                  --message "A new Frontend Image pushed by ${{ github.actor }}. Repository: ${{ github.repository }}"
    
    build-backend:
        name: Build and Push Backend Image to ECR
        runs-on: ubuntu-latest
        needs: [test]
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Generate image metadata
              id: meta
              run: |
                SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
                echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
                echo "Image tag: ${SHORT_SHA}"

              
            - name: Build & Push Loruki Backend Image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: hexagon-ecr
                IMAGE_TAG: loruki_backend
              run: |
                docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend/
                docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-${{ github.run_number }}
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-${{ github.run_number }}

            - name: Notify ECR Push
              run: |
                aws sns publish \
                  --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
                  --subject "New Loruki Image Pushed to ECR" \
                  --message "A new Backend Image pushed by ${{ github.actor }}. Repository: ${{ github.repository }}"


    pull_postgres:
        name: Pull and Push Postgres Image to ECR
        runs-on: ubuntu-latest
        needs: [test]
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Generate image metadata
              id: meta
              run: |
                SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
                echo "tag=${SHORT_SHA}" >> $GITHUB_OUTPUT
                echo "Image tag: ${SHORT_SHA}"

              
            - name: Build & Push Postgres Database Image
              env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                ECR_REPOSITORY: hexagon-ecr
                IMAGE_TAG: postgres_db
              run: |
                docker pull postgres:16-alpine
                docker tag postgres:16-alpine $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-16
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG-16


            - name: Notify ECR Push
              run: |
                aws sns publish \
                  --topic-arn ${{ secrets.SNS_TOPIC_ARN }} \
                  --subject "New Loruki Image Pushed to ECR" \
                  --message "A new Postgres Image pushed by ${{ github.actor }}. Repository: ${{ github.repository }}"







            


            
